services:
  Github\Client:
    arguments:
      - '@Github\HttpClient\Builder'
    calls:
      - [ 'authenticate', [ '%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%' ] ]

  Github\HttpClient\Builder:
    arguments:
      - '@Psr\Http\Client\ClientInterface'
