nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type']
        expose_headers: ['Link']
        max_age: 3600
    paths:
      '^/email/send':
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['POST', 'OPTIONS']
        allow_headers: ['Content-Type']
        max_age: 3600
