nelmio_cors:
  defaults:
    allow_origin: [ '*' ]
    allow_methods: [ 'GET', 'OPTIONS' ]
    allow_headers: [ 'Content-Type' ]
    expose_headers: [ ]
    max_age: 3600
  paths:
    '^/email/send':
      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_methods: [ 'POST', 'OPTIONS' ]
      allow_headers: [ 'Content-Type' ]
      max_age: 3600
