sudo: false

language: php

php:
  - 7.3

git:
  depth: 1

before_install:
  - mkdir -p ./coverage
install:
  - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

script:
  - php vendor/bin/phpcs -q --standard=ruleset.xml --runtime-set ignore_warnings_on_exit true
  - php vendor/bin/simple-phpunit -c phpunit.xml.dist
