version: "3.6"

services:
  api-elliotjreed:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api-elliotjreed
    restart: always
    networks:
      - elliotjreed
      - web
    ports:
      - "5000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.elliotjreed.com"
      - "traefik.protocol=http"
      - "traefik.port=5000"

networks:
  elliotjreed:
    name: elliotjreed
  web:
    external: true
