version: "3.6"

services:
  elliotjreed-api-php:
    image: elliotjreed/elliotjreed-api-php:feature-php
    container_name: elliotjreed-api-php
    restart: always
    networks:
      - elliotjreed-api
    volumes:
      - ./.env.local:/var/www/html/.env

  elliotjreed-api-nginx:
    image: elliotjreed/elliotjreed-api-nginx:feature-php
    container_name: elliotjreed-api-nginx
    restart: always
    volumes:
      - ./.env.local:/var/www/html/.env.local:ro
    networks:
      - elliotjreed-api
      - web
    depends_on:
      - elliotjreed-api-php
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.elliotjreed.com"
      - "traefik.protocol=h2c"
      - "traefik.port=96"

networks:
  web:
    external: true
  elliotjreed-api:
    name: elliotjreed-api

