services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\Mailer\MailerInterface:
    class: App\Tests\Double\Mailer\EmailSpy

  Github\Api\Repository\Contents:
    class: App\Tests\Double\Github\Contents

  Github\Api\Repo:
    class: App\Tests\Double\Github\Repo
    arguments:
      $contents: '@Github\Api\Repository\Contents'

  Github\Client:
    class: App\Tests\Double\Github\Client
    arguments:
      $repo: '@Github\Api\Repo'

  hcaptchaMockResponse:
    class: Symfony\Component\HttpClient\Response\MockResponse
    arguments:
      $body: '{"success": true}'

  hcaptchaMockHttpClient:
    class: Symfony\Component\HttpClient\MockHttpClient
    arguments:
      $responseFactory: '@hcaptchaMockResponse'

  App\Validator\Captcha:
    arguments:
      $httpClient: '@hcaptchaMockHttpClient'
